-- Create registro table
CREATE TABLE IF NOT EXISTS registro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL,
  poke1 VARCHAR(255) NOT NULL,
  poke2 VARCHAR(255) NOT NULL,
  poke3 VARCHAR(255) NOT NULL,
  poke4 VARCHAR(255) NOT NULL,
  poke5 VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);